services:
  web:
    build: ./web
    depends_on:
      - crdt

  crdt:
    build: ./crdt

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - crdt
      - web
